public class binatang{
	public static void main(String[] args) {
		System.out.println("");
		System.out.println("");
		System.out.println("         \' \'         \' \'         \'-\'         \' \'");
		System.out.println("         ~~~~          ~~~~          ~~~~          ~~~~");
		System.out.println("         (oo)          (oo)          (oo)          (oo)");
		System.out.println("  +=======\\/    +=======\\/    +=======\\/    +=======\\/");
		System.out.println(" / ||-&&&-||   / ||-&&&-||   / ||-&&&-||   / ||-&&&-||");
		System.out.println("*  ||     ||  *  ||     ||  *  ||     ||  *  ||     ||");
		System.out.println("   \"\"     \"\"     \"\"     \"\"     \"\"     \"\"     \"\"     \"\"");
		System.out.println("");
		System.out.println("");
		System.out.println("         ~~~~          ~~~~          ~~~~          ~~~~");
		System.out.println("         (oo)          (oo)          (oo)          (oo)");
		System.out.println("  +=======\\/    +=======\\/    +=======\\/    +=======\\/");
		System.out.println(" / ||-&&&-||   / ||-&&&-||   / ||-&&&-||   / ||-&&&-||");
		System.out.println("*  ||     ||  *  ||     ||  *  ||     ||  *  ||     ||");
		System.out.println("   \"\"     \"\"     \"\"     \"\"     \"\"     \"\"     \"\"     \"\"");
		System.out.println("");
		System.out.println("");
		System.out.println("         ~~~~          ~~~~          ~~~~          ~~~~");
		System.out.println("         (oo)          (oo)          (oo)          (oo)");
		System.out.println("  +=======\\/    +=======\\/    +=======\\/    +=======\\/");
		System.out.println(" / ||-&&&-||   / ||-&&&-||   / ||-&&&-||   / ||-&&&-||");
		System.out.println("*  ||     ||  *  ||     ||  *  ||     ||  *  ||     ||");
		System.out.println("   \"\"     \"\"     \"\"     \"\"     \"\"     \"\"     \"\"     \"\"");
		System.out.println("");
		System.out.println("");
		System.out.println("         ~~~~          ~~~~          ~~~~          ~~~~");
		System.out.println("         (oo)          (oo)          (oo)          (oo)");
		System.out.println("  +=======\\/    +=======\\/    +=======\\/    +=======\\/");
		System.out.println(" / ||-&&&-||   / ||-&&&-||   / ||-&&&-||   / ||-&&&-||");
		System.out.println("*  ||     ||  *  ||     ||  *  ||     ||  *  ||     ||");
		System.out.println("   \"\"     \"\"     \"\"     \"\"     \"\"     \"\"     \"\"     \"\"");
		System.out.println("");
		System.out.println("");
		System.out.println("         ~~~~          ~~~~          ~~~~          ~~~~");
		System.out.println("         (oo)          (oo)          (oo)          (oo)");
		System.out.println("  +=======\\/    +=======\\/    +=======\\/    +=======\\/");
		System.out.println(" / ||-&&&-||   / ||-&&&-||   / ||-&&&-||   / ||-&&&-||");
		System.out.println("*  ||     ||  *  ||     ||  *  ||     ||  *  ||     ||");
		System.out.println("   \"\"     \"\"     \"\"     \"\"     \"\"     \"\"     \"\"     \"\"");
		System.out.println("");
		System.out.println("");
		System.out.println("         ~~~~          ~~~~          ~~~~          ~~~~");
		System.out.println("         (oo)          (oo)          (oo)          (oo)");
		System.out.println("  +=======\\/    +=======\\/    +=======\\/    +=======\\/");
		System.out.println(" / ||-&&&-||   / ||-&&&-||   / ||-&&&-||   / ||-&&&-||");
		System.out.println("*  ||     ||  *  ||     ||  *  ||     ||  *  ||     ||");
		System.out.println("   \"\"     \"\"     \"\"     \"\"     \"\"     \"\"     \"\"     \"\"");
		System.out.println("");
		System.out.println("");
		System.out.println("         ~~~~          ~~~~          ~~~~          ~~~~");
		System.out.println("         (oo)          (oo)          (oo)          (oo)");
		System.out.println("  +=======\\/    +=======\\/    +=======\\/    +=======\\/");
		System.out.println(" / ||-&&&-||   / ||-&&&-||   / ||-&&&-||   / ||-&&&-||");
		System.out.println("*  ||     ||  *  ||     ||  *  ||     ||  *  ||     ||");
		System.out.println("   \"\"     \"\"     \"\"     \"\"     \"\"     \"\"     \"\"     \"\"");
		System.out.println("");
		System.out.println("");
		System.out.println("         ~~~~          ~~~~          ~~~~          ~~~~");
		System.out.println("         (oo)          (oo)          (oo)          (oo)");
		System.out.println("  +=======\\/    +=======\\/    +=======\\/    +=======\\/");
		System.out.println(" / ||-&&&-||   / ||-&&&-||   / ||-&&&-||   / ||-&&&-||");
		System.out.println("*  ||     ||  *  ||     ||  *  ||     ||  *  ||     ||");
		System.out.println("");
		System.out.println("");
		System.out.println("         ~~~~          ~~~~          ~~~~          ~~~~");
		System.out.println("         (oo)          (oo)          (oo)          (oo)");
		System.out.println("  +=======\\/    +=======\\/    +=======\\/    +=======\\/");
		System.out.println(" / ||-&&&-||   / ||-&&&-||   / ||-&&&-||   / ||-&&&-||");
		System.out.println("*  ||     ||  *  ||     ||  *  ||     ||  *  ||     ||");
		System.out.println("");
		System.out.println("");
		System.out.println("         ~~~~          ~~~~          ~~~~          ~~~~");
		System.out.println("         (oo)          (oo)          (oo)          (oo)");
		System.out.println("  +=======\\/    +=======\\/    +=======\\/    +=======\\/");
		System.out.println(" / ||-&&&-||   / ||-&&&-||   / ||-&&&-||   / ||-&&&-||");
		System.out.println("*  ||     ||  *  ||     ||  *  ||     ||  *  ||     ||");
		System.out.println("   \"\"     \"\"     \"\"     \"\"     \"\"     \"\"     \"\"     \"\"");System.out.println("   \"\"     \"\"     \"\"     \"\"     \"\"     \"\"     \"\"     \"\"");System.out.println("   \"\"     \"\"     \"\"     \"\"     \"\"     \"\"     \"\"     \"\"");
	}
}